export const GET_VIDEOGAMES = "GET_VIDEOGAMES";
export const GET_VIDEOGAME_NAMES = "GET_VIDEOGAME_NAMES";
export const FILTER_BY_GENRE = "FILTER_BY_GENRE";
export const ORDER_BY_RATING = "ORDER_BY_RATING"
export const FILTER_CREATED = "FILTER_CREATED";
export const ORDER_BY_NAME = "ORDER_BY_NAME";